version: "3.9"
services:
  fitness_foods-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness_foods-prod
    ports:
      - 4000:4000
    working_dir: /usr/src
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: mongodb+srv://admin:5cB6LelZ1s1nxwCw@mb-labs-api-cluster.ek7z23k.mongodb.net/fitness_foods-api?retryWrites=true&w=majority
      DB_NAME: fitness_foods-api
    volumes:
      - /usr/local/data:/var/lib/mongodb/data

