const line = {
  code: '"0008725070018',
  url: "http: //world-en.openfoodfacts.org/product/0008725070018/long-grove-confectionery-co-graham-crackers-milk-chocolate",
  creator: "usda-ndb-import",
  created_t: "1489071832",
  created_datetime: "2017-03-09T15: 03: 52Z",
  last_modified_t: "1489071832",
  last_modified_datetime: "2017-03-09T15: 03: 52Z",
  product_name: "Long Grove Confectionery Co., Graham Crackers, Milk Chocolate",
  abbreviated_product_name: "",
  generic_name: "",
  quantity: "",
  packaging: "",
  packaging_tags: "",
  packaging_text: "",
  brands: "Long Grove Confectionery Co.",
  brands_tags: "long-grove-confectionery-co",
  categories: "",
  categories_tags: "",
  categories_en: "",
  origins: "",
  origins_tags: "",
  origins_en: "",
  manufacturing_places: "",
  manufacturing_places_tags: "",
  labels: "",
  labels_tags: "",
  labels_en: "",
  emb_codes: "",
  emb_codes_tags: "",
  first_packaging_code_geo: "",
  cities: "",
  cities_tags: "",
  purchase_places: "",
  stores: "",
  countries: "United States",
  countries_tags: "en:united-states",
  countries_en: "United States",
  ingredients_text:
    "Milk chocolate (sugar, whole milk, cocoa butter, chocolate liquor, soy lecithin [emulsifier], vanilla), graham cracker (whole wheat flour, enriched flour [wheat flour, niacin, reduced iron, thiamin mononitrate [vitamin b1], riboflavin [vitamin b2], folic",
  allergens: "",
  allergens_en: "",
  traces: "",
  traces_tags: "",
  traces_en: "",
  serving_size: "28 g (1 PC.)",
  serving_quantity: "28",
  no_nutriments: "",
  additives_n: "1",
  additives: "",
  additives_tags: "en:e322,en:e322i",
  additives_en: "E322 - Lecithins,E322i - Lecithin",
  ingredients_from_palm_oil_n: "0",
  ingredients_from_palm_oil: "",
  ingredients_from_palm_oil_tags: "",
  ingredients_that_may_be_from_palm_oil_n: "0",
  ingredients_that_may_be_from_palm_oil: "",
  ingredients_that_may_be_from_palm_oil_tags: "",
  nutriscore_score: "",
  nutriscore_grade: "",
  nova_group: "4",
  pnns_groups_1: "unknown",
  pnns_groups_2: "unknown",
  states:
    "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-uploaded",
  states_tags:
    "en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-uploaded",
  states_en:
    "To be completed,Nutrition facts completed,Ingredients completed,Expiration date to be completed,Packaging code to be completed,Characteristics to be completed,Categories to be completed,Brands completed,Packaging to be completed,Quantity to be completed,Product name completed,Photos to be uploaded",
  brand_owner: "",
  main_category: "",
  main_category_en: "",
  image_url: "",
  image_small_url: "",
  image_ingredients_url: "",
  image_ingredients_small_url: "",
  image_nutrition_url: "",
  image_nutrition_small_url: "",
  "energy-kj_100g": "",
  "energy-kcal_100g": "536",
  energy_100g: "2243",
  "energy-from-fat_100g": "",
  fat_100g: "28.57",
  "saturated-fat_100g": "16.07",
  "-butyric-acid_100g": "",
  "-caproic-acid_100g": "",
  "-caprylic-acid_100g": "",
  "-capric-acid_100g": "",
  "-lauric-acid_100g": "",
  "-myristic-acid_100g": "",
  "-palmitic-acid_100g": "",
  "-stearic-acid_100g": "",
  "-arachidic-acid_100g": "",
  "-behenic-acid_100g": "",
  "-lignoceric-acid_100g": "",
  "-cerotic-acid_100g": "",
  "-montanic-acid_100g": "",
  "-melissic-acid_100g": "",
  "monounsaturated-fat_100g": "",
  "polyunsaturated-fat_100g": "",
  "omega-3-fat_100g": "",
  "-alpha-linolenic-acid_100g": "",
  "-eicosapentaenoic-acid_100g": "",
  "-docosahexaenoic-acid_100g": "",
  "omega-6-fat_100g": "",
  "-linoleic-acid_100g": "",
  "-arachidonic-acid_100g": "",
  "-gamma-linolenic-acid_100g": "",
  "-dihomo-gamma-linolenic-acid_100g": "",
  "omega-9-fat_100g": "",
  "-oleic-acid_100g": "",
  "-elaidic-acid_100g": "",
  "-gondoic-acid_100g": "",
  "-mead-acid_100g": "",
  "-erucic-acid_100g": "",
  "-nervonic-acid_100g": "",
  "trans-fat_100g": "0",
  cholesterol_100g: "0.018",
  carbohydrates_100g: "64.29",
  sugars_100g: "46.43",
  "-sucrose_100g": "",
  "-glucose_100g": "",
  "-fructose_100g": "",
  "-lactose_100g": "",
  "-maltose_100g": "",
  "-maltodextrins_100g": "",
  starch_100g: "",
  polyols_100g: "",
  fiber_100g: "3.6",
  "-soluble-fiber_100g": "",
  "-insoluble-fiber_100g": "",
  proteins_100g: "7.14",
  casein_100g: "",
  "serum-proteins_100g": "",
  nucleotides_100g: "",
  salt_100g: "0.45466",
  sodium_100g: "0.181864",
  alcohol_100g: "",
  "vitamin-a_100g": "0.0002142",
  "beta-carotene_100g": "",
  "vitamin-d_100g": "",
  "vitamin-e_100g": "",
  "vitamin-k_100g": "",
  "vitamin-c_100g": "0",
  "vitamin-b1_100g": "",
  "vitamin-b2_100g": "",
  "vitamin-pp_100g": "",
  "vitamin-b6_100g": "",
  "vitamin-b9_100g": "",
  folates_100g: "",
  "vitamin-b12_100g": "",
  biotin_100g: "",
  "pantothenic-acid_100g": "",
  silica_100g: "",
  bicarbonate_100g: "",
  potassium_100g: "",
  chloride_100g: "",
  calcium_100g: "0.286",
  phosphorus_100g: "",
  iron_100g: "0.00129",
  magnesium_100g: "",
  zinc_100g: "",
  copper_100g: "",
  manganese_100g: "",
  fluoride_100g: "",
  selenium_100g: "",
  chromium_100g: "",
  molybdenum_100g: "",
  iodine_100g: "",
  caffeine_100g: "",
  taurine_100g: "",
  ph_100g: "",
  "fruits-vegetables-nuts_100g": "",
  "fruits-vegetables-nuts-dried_100g": "",
  "fruits-vegetables-nuts-estimate_100g": "",
  "collagen-meat-protein-ratio_100g": "",
  cocoa_100g: "",
  chlorophyl_100g: "",
  "carbon-footprint_100g": "",
  "carbon-footprint-from-meat-or-fish_100g": "",
  "nutrition-score-fr_100g": "",
  "nutrition-score-uk_100g": "",
  "glycemic-index_100g": "",
  "water-hardness_100g": "",
  choline_100g: "",
  phylloquinone_100g: "",
  "beta-glucan_100g": "",
  inositol_100g: "",
  carnitine_100g: '";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\r',
};
