import { Product } from "@prisma/client";

export const returnArrayOf5Products = (): Product[] => {
  return [
    {
      id: "636174caa7856a4941684bc1",
      imported_t: new Date("2022-11-01T19:34:34.385Z"),
      updatedAt: new Date("2022-11-01T19:37:48.138Z"),
      status: "published",
      code: "0815360014631",
      url: "http://world_en.openfoodfacts.org/product/0815360014631/berry_lattice_pie",
      creator: "org_database_usda",
      created_t: "1587644821",
      last_modified_t: "1587644821",
      product_name: "Berry lattice pie",
      quantity: "",
      brands: "",
      categories: "Biscuits and cakes, Cakes",
      labels: "",
      cities: "",
      purchase_places: "",
      stores: "",
      ingredients_text:
        "Blackberries, water, enriched flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), sugar, palm oil, food starch_modified, contains less than 2% of: salt, dextrose, corn syrup, sorbic acid, apple cider vinegar, carob bean gum, cellulose gum, agar, calcium propionate.",
      traces: "",
      serving_size: "0.2 PIE (136 g)",
      serving_quantity: "136",
      nutriscore_score: "13",
      nutriscore_grade: "d",
      main_category: "en:cakes",
      image_url: "",
    },
    {
      id: "636174cba7856a4941684bc5",
      imported_t: new Date("2022-11-01T19:34:34.386Z"),
      updatedAt: new Date("2022-11-01T19:37:48.139Z"),
      status: "published",
      code: "0815360014655",
      url: "http://world_en.openfoodfacts.org/product/0815360014655/mince_pie",
      creator: "org_database_usda",
      created_t: "1587642295",
      last_modified_t: "1587642295",
      product_name: "Mince pie",
      quantity: "",
      brands: "",
      categories: "Biscuits and cakes, Cakes, Cooking helpers, Dessert mixes, Pastry helpers, Cake mixes",
      labels: "",
      cities: "",
      purchase_places: "",
      stores: "",
      ingredients_text:
        "Water, enriched flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), apples, palm oil, raisins, sugar, food starch_modified, corn syrup, pineapple, contains 2% or less of: egg, apple cider vinegar, salt, dextrose, spices, natural and artificial flavor, ascorbic acid, citric acid, potassium sorbate and calcium propionate (to preserve freshness).",
      traces: "",
      serving_size: "0.2 PIE (136 g)",
      serving_quantity: "136",
      nutriscore_score: "",
      nutriscore_grade: "",
      main_category: "en:cake_mixes",
      image_url: "",
    },
    {
      id: "636174cba7856a4941684bc9",
      imported_t: new Date("2022-11-01T19:34:34.387Z"),
      updatedAt: new Date("2022-11-01T19:37:48.140Z"),
      status: "published",
      code: "0815360014662",
      url: "http://world_en.openfoodfacts.org/product/0815360014662/pie",
      creator: "org_database_usda",
      created_t: "1587641704",
      last_modified_t: "1587641704",
      product_name: "PIE",
      quantity: "",
      brands: "",
      categories: "Biscuits and cakes, Cakes",
      labels: "",
      cities: "",
      purchase_places: "",
      stores: "",
      ingredients_text:
        "Water, pumpkin, sugar, enriched flour (flour niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), palm oil, eggs, corn syrup, nonfat milk, food starch_modified, contains less than 2% of: whey, salt, dextrose, sorbic acid, soybean oil, cinnamon, spices, carob bean gum, cellulose gum, agar, apple cider vinegar, calcium propionate.",
      traces: "",
      serving_size: "0.111 PIE (120 g)",
      serving_quantity: "120",
      nutriscore_score: "13",
      nutriscore_grade: "d",
      main_category: "en:cakes",
      image_url: "",
    },
    {
      id: "636174cba7856a4941684bcf",
      imported_t: new Date("2022-11-01T19:34:34.387Z"),
      updatedAt: new Date("2022-11-01T19:37:48.140Z"),
      status: "published",
      code: "0815360014679",
      url: "http://world_en.openfoodfacts.org/product/0815360014679/chocolate_pecan_pie",
      creator: "org_database_usda",
      created_t: "1587641701",
      last_modified_t: "1587641701",
      product_name: "Chocolate pecan pie",
      quantity: "",
      brands: "",
      categories: "Biscuits and cakes, Cakes",
      labels: "",
      cities: "",
      purchase_places: "",
      stores: "",
      ingredients_text:
        "Water, sugar, enriched flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), corn syrup, pecans, eggs, palm oil, maltodextrin, caramel, contains less than 2% of: food starch_modified, salt, dextrose, caramel color. sorbic acid, cocoa (processed with alkali), artificial color (blue 1, red 40, yellow 5), gums (agar, cellulose, locust bean), hydrogenated cottonseed oil, phosphoric acid, polysorbate 60, sodium benzoate, sorbitan monostearate, tetrasodium pyrophosphate, natural and artificial flavors, potassium sorbate, apple cider vinegar, calcium propionate.",
      traces: "",
      serving_size: "0.2 PIE (125 g)",
      serving_quantity: "125",
      nutriscore_score: "13",
      nutriscore_grade: "d",
      main_category: "en:cakes",
      image_url: "",
    },
    {
      id: "636174cba7856a4941684bd5",
      imported_t: new Date("2022-11-01T19:34:34.388Z"),
      updatedAt: new Date("2022-11-01T19:37:48.141Z"),
      status: "published",
      code: "0815360014891",
      url: "http://world_en.openfoodfacts.org/product/0815360014891/galette",
      creator: "org_database_usda",
      created_t: "1587656057",
      last_modified_t: "1587656057",
      product_name: "Galette",
      quantity: "",
      brands: "",
      categories: "Biscuits and cakes, Pastries",
      labels: "",
      cities: "",
      purchase_places: "",
      stores: "",
      ingredients_text:
        "Pineapple, enriched flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), water, sugar, palm oil, corn syrup, cherries, food starch_modified, contains less than 2% of: high fructose corn syrup, salt, dextrose, soy lecithin, corn starch, carob bean gum, cellulose gum, agar, apple cider vinegar, sorbic acid, calcium propionate.",
      traces: "",
      serving_size: "0.1 PIE (119 g)",
      serving_quantity: "119",
      nutriscore_score: "8",
      nutriscore_grade: "c",
      main_category: "en:pastries",
      image_url: "",
    },
  ];
};

export const returnOneProduct = (): Product => {
  return {
    id: "636174cba7856a4941684bc5",
    imported_t: new Date("2022-11-01T19:34:34.386Z"),
    updatedAt: new Date("2022-11-01T19:37:48.139Z"),
    status: "published",
    code: "0815360014655",
    url: "http://world_en.openfoodfacts.org/product/0815360014655/mince_pie",
    creator: "org_database_usda",
    created_t: "1587642295",
    last_modified_t: "1587642295",
    product_name: "Mince pie",
    quantity: "",
    brands: "",
    categories: "Biscuits and cakes, Cakes, Cooking helpers, Dessert mixes, Pastry helpers, Cake mixes",
    labels: "",
    cities: "",
    purchase_places: "",
    stores: "",
    ingredients_text:
      "Water, enriched flour (flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), apples, palm oil, raisins, sugar, food starch_modified, corn syrup, pineapple, contains 2% or less of: egg, apple cider vinegar, salt, dextrose, spices, natural and artificial flavor, ascorbic acid, citric acid, potassium sorbate and calcium propionate (to preserve freshness).",
    traces: "",
    serving_size: "0.2 PIE (136 g)",
    serving_quantity: "136",
    nutriscore_score: "",
    nutriscore_grade: "",
    main_category: "en:cake_mixes",
    image_url: "",
  }
}